name: GitHub metrics
on:
  schedule:
    - cron: "0 0 * * *" 
  push:
    branches: "main"
jobs:
# The job below generates the images displayed on lowlighter/lowlighter
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
  
      - name: Personal metrics
        uses: Dialca/metrics@master
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, activity, community, repositories"
          plugin_lines: yes
          plugin_music: yes
          plugin_music_playlist: ${{ secrets.MUSIC_PLAYLIST }}
          plugin_music_limit: 2
          plugin_isocalendar: yes
          plugin_topics: yes
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugins_errors_fatal: yes
          
      - name: Personal metrics (detailed)
        uses: Dialca/metrics@master
        with:
          filename: metrics.detailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "metadata"
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_gists: yes
          plugin_followup: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugins_errors_fatal: yes
          
# The job below generates the images displayed on lowlighter/metrics
  github-metrics:
    needs: [github-metrics-personal]
    runs-on: ubuntu-latest
    steps:

      - name: Classic template
        uses: Dialca/metrics@master
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, repositories"
          plugin_lines: yes
          plugins_errors_fatal: yes

      - name: Terminal template
        uses: Dialca/metrics@master
        with:
          template: terminal
          filename: metrics.terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, metadata"
          plugins_errors_fatal: yes

      - name: PageSpeed plugin
        uses: Dialca/metrics@master
        with:
          filename: metrics.plugin.pagespeed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugins_errors_fatal: yes

      - name: PageSpeed plugin (detailed)
        uses: Dialca/metrics@master
        with:
          filename: metrics.plugin.pagespeed.detailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugins_errors_fatal: yes

      - name: Music plugin (playlist)
        uses: Dialca/metrics@master
        with:
          filename: metrics.plugin.music.playlist.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_music: yes
          plugin_music_mode: playlist
          plugin_music_playlist: ${{ secrets.MUSIC_PLAYLIST }}
          plugin_music_limit: 2
          plugins_errors_fatal: yes

      - name: Music plugin (recent)
        uses: Dialca/metrics@master
        with:
          filename: metrics.plugin.music.recent.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_limit: 2
          plugins_errors_fatal: yes

      - name: Habits plugin
        uses: Dialca/metrics@master
        with:
          filename: metrics.plugin.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugins_errors_fatal: yes
                    
      - name: Habits plugin (facts)
        uses: Dialca/metrics@master
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugins_errors_fatal: yes
          
      - name: Habits plugin (charts)
        uses: Dialca/metrics@master
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugins_errors_fatal: yes

      - name: Languages plugin
        uses: Dialca/metrics@master
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_languages: yes
          plugins_errors_fatal: yes

      - name: Follow-up plugin
        uses: Dialca/metrics@master
        with:
          filename: metrics.plugin.followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_followup: yes
          plugins_errors_fatal: yes

      - name: Lines plugin
        uses: Dialca/metrics@master
        with:
          filename: metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "repositories"
          plugin_lines: yes
          plugins_errors_fatal: yes

      - name: Traffic plugin
        uses: Dialca/metrics@master
        with:
          filename: metrics.plugin.traffic.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "repositories"
          plugin_traffic: yes
          plugins_errors_fatal: yes

      - name: Posts plugin
        uses: Dialca/metrics@master
        with:
          filename: metrics.plugin.posts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugins_errors_fatal: yes

      - name: Isocalendar plugin
        uses: Dialca/metrics@master
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugins_errors_fatal: yes

      - name: Isocalendar plugin (full year)
        uses: Dialca/metrics@master
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugins_errors_fatal: yes

      - name: Gists plugin
        uses: Dialca/metrics@master
        with:
          filename: metrics.plugin.gists.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_gists: yes
          plugins_errors_fatal: yes

      - name: Topics plugin
        uses: Dialca/metrics@master
        with:
          filename: metrics.plugin.topics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_topics: yes
          plugins_errors_fatal: yes

      - name: Projects plugin
        uses: Dialca/metrics@master
        with:
          filename: metrics.plugin.projects.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_projects: yes
          plugins_errors_fatal: yes

      - name: Tweets plugin
        uses: Dialca/metrics@master
        with:
          filename: metrics.plugin.tweets.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugins_errors_fatal: yes

      - name: Header (additional features)
        uses: Dialca/metrics@master
        with:
          filename: metrics.header.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header"
          debug_flags: --cakeday --hireable
          plugins_errors_fatal: yes
